name: Deploy Lambda with Docker Image

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: sithuramyo/lawkanat-backend-app
      AWS_REGION: ap-southeast-1
      FUNCTION_NAME: lawkanat-backend

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:${{ github.ref_name }} .

      - name: Push Docker image
        run: docker push $IMAGE_NAME:${{ github.ref_name }}

      - name: Deploy to AWS Lambda using Docker image
        run: |
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --image-uri $IMAGE_NAME:${{ github.ref_name }} \
            --region $AWS_REGION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
