name: Pull Request Build & Test

on:
  pull_request:
    branches:
      - development
      - deployment
    

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet test --no-build --configuration Release --logger trx --results-directory TestResults

      - name: Test
        run: dotnet test --no-build --configuration Release --logger trx --results-directory TestResults

      - name: Code Quality Check
        run: dotnet format student-management-app-backend.sln --verify-no-changes
