name: Auto Merge to Development

on:
  pull_request:
    types: [closed]
    branches:
      - development

jobs:
  auto-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge confirmation
        run: echo "✅ PR was merged into development."
